version: '3.8'

services:
  discord-bot:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: discord-bot-container
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./app:/usr/src/app
    restart: unless-stopped
